version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 7
    groups:
      dev:
        dependency-type: development
        exclude-patterns:
          - "@cloudflare/workers-types"
          - wrangler
      wrangler:
        patterns:
          - "@cloudflare/workers-types"
          - wrangler
