name = "inialum-mail-service"
compatibility_date = "2024-01-01"
node_compat = true
workers_dev = false
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "inialum-mail-service-staging"
vars = { ENVIRONMENT = "staging" }
